name: realtime-currency-exchange

services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    env_file: .env
    environment:
      OPEN_EXCHANGE_RATES_HOST_URL: https://openexchangerates.org/api
      OPEN_EXCHANGE_RATES_APP_ID: ${OPEN_EXCHANGE_RATES_APP_ID}
      REDIS_HOST_URL: redis://redis:6379
    ports:
      - '5000:5000'
    depends_on:
      - redis
  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    environment:
      SOCKET_SERVER_HOST_URL: http://127.0.0.1:5000
    ports:
      - '3000:3000'
    depends_on:
      - backend
  redis:
    image: redis:7.2.1
    ports:
      - '127.0.0.1:6380:6379'
    volumes:
      - './redis.conf:/usr/local/etc/redis/redis.conf'
    command: redis-server /usr/local/etc/redis/redis.conf
